service: shilpagya  # Your project name

provider:
  name: aws
  runtime: nodejs18.x
  region: ca-central-1  # Change if needed
  memorySize: 800  # Adjust based on your app needs
  timeout: 30  # Increase timeout for SSR
  environment:
    NODE_ENV: production

functions:
  nextjsApp:
    handler: handler.handler  # Ensure handler.js exists in your project
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-nextjs

custom:
  serverless-nextjs:
    memory: 800
    timeout: 30
    name: shilpagya
    bucketName: shilpagya-deployment

